<?php
/**
 * Report Generation API
 * Generates PDF and Excel reports from activity logs
 */

header('Content-Type: application/json');
session_start();

// Check authentication
if (!isset($_SESSION['user_id'])) {
    http_response_code(401);
    echo json_encode(array('error' => 'Unauthorized'));
    exit;
}

$format = isset($_POST['format']) ? sanitize($_POST['format']) : 'csv';
$dateFrom = isset($_POST['date_from']) ? sanitize($_POST['date_from']) : date('Y-m-d', strtotime('-30 days'));
$dateTo = isset($_POST['date_to']) ? sanitize($_POST['date_to']) : date('Y-m-d');
$actionFilter = isset($_POST['action_filter']) ? sanitize($_POST['action_filter']) : '';

// Sample data - in production, fetch from database
$activities = array(
    array('time' => '2026-07-12 06:42:15', 'user' => 'James Carter', 'role' => 'Administrator', 'action' => 'User Login', 'details' => 'Successful login from admin console', 'status' => 'success'),
    array('time' => '2026-07-12 07:11:32', 'user' => 'Rina Shah', 'role' => 'Security Officer', 'action' => 'Camera Added', 'details' => 'Lobby North added to perimeter group', 'status' => 'info'),
    array('time' => '2026-07-12 08:00:48', 'user' => 'Owen Price', 'role' => 'Viewer', 'action' => 'Recording Downloaded', 'details' => 'Playback clip exported locally (142 MB)', 'status' => 'success'),
    array('time' => '2026-07-12 08:45:22', 'user' => 'System', 'role' => 'System', 'action' => 'Motion Detected', 'details' => 'Movement detected in Parking Lot camera', 'status' => 'warning'),
    array('time' => '2026-07-12 09:15:10', 'user' => 'James Carter', 'role' => 'Administrator', 'action' => 'Alert Sent', 'details' => 'Email alert sent to security@company.com', 'status' => 'success'),
);

// Filter activities by date range
$filtered = array_filter($activities, function($a) use ($dateFrom, $dateTo) {
    $actDate = substr($a['time'], 0, 10);
    return $actDate >= $dateFrom && $actDate <= $dateTo;
});

if ($actionFilter) {
    $filtered = array_filter($filtered, function($a) use ($actionFilter) {
        return stripos($a['action'], $actionFilter) !== false;
    });
}

switch ($format) {
    case 'pdf':
        generatePDF($filtered, $dateFrom, $dateTo);
        break;
    case 'excel':
        generateExcel($filtered, $dateFrom, $dateTo);
        break;
    case 'csv':
    default:
        generateCSV($filtered);
        break;
}

function generateCSV($data) {
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="activity-report-' . date('Y-m-d-His') . '.csv"');
    
    $output = fopen('php://output', 'w');
        fputcsv($output, array('Time', 'User', 'Role', 'Action', 'Details', 'Status'));
    
    foreach ($data as $row) {
        fputcsv($output, array(
            $row['time'],
            $row['user'],
            $row['role'],
            $row['action'],
            $row['details'],
            $row['status']
        ));
    }
    
    fclose($output);
    exit;
}

function generateExcel($data, $dateFrom, $dateTo) {
    // Generate simple HTML table that can be saved as Excel
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment; filename="activity-report-' . date('Y-m-d-His') . '.xls"');
    
    echo '<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <style>
            body { font-family: Arial, sans-serif; }
            table { border-collapse: collapse; width: 100%; }
            th, td { border: 1px solid #000; padding: 8px; text-align: left; }
            th { background-color: #4472C4; color: white; font-weight: bold; }
            tr:nth-child(even) { background-color: #f2f2f2; }
            .title { font-size: 16px; font-weight: bold; margin-bottom: 20px; }
            .info { font-size: 12px; color: #666; margin-bottom: 10px; }
        </style>
    </head>
    <body>
        <div class="title">SecureVision - Activity Report</div>
        <div class="info">
            Report Generated: ' . date('Y-m-d H:i:s') . '<br>
            Period: ' . $dateFrom . ' to ' . $dateTo . '<br>
            Generated by: ' . (isset($_SESSION['user_name']) ? htmlspecialchars($_SESSION['user_name']) : 'System') . '
        </div>
        <table>
            <thead>
                <tr>
                    <th>Time</th>
                    <th>User</th>
                    <th>Role</th>
                    <th>Action</th>
                    <th>Details</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>';
    
    foreach ($data as $row) {
        echo '<tr>
                <td>' . htmlspecialchars($row['time']) . '</td>
                <td>' . htmlspecialchars($row['user']) . '</td>
                <td>' . htmlspecialchars($row['role']) . '</td>
                <td>' . htmlspecialchars($row['action']) . '</td>
                <td>' . htmlspecialchars($row['details']) . '</td>
                <td>' . htmlspecialchars($row['status']) . '</td>
            </tr>';
    }
    
    echo '      </tbody>
        </table>
        <div class="info" style="margin-top: 20px;">
            Total Records: ' . count($data) . '
        </div>
    </body>
    </html>';
    exit;
}

function generatePDF($data, $dateFrom, $dateTo) {
    // Generate PDF using HTML content
    // For production, use a library like TCPDF or FPDF
    
    ob_start();
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Activity Report</title>
        <style>
            * { margin: 0; padding: 0; }
            body { font-family: Arial, sans-serif; color: #333; line-height: 1.6; }
            .container { max-width: 900px; margin: 0 auto; padding: 20px; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
            .header h1 { font-size: 24px; margin-bottom: 5px; }
            .header p { color: #666; font-size: 12px; }
            .info-box { background: #f5f5f5; padding: 10px; margin-bottom: 20px; font-size: 11px; }
            .info-box p { margin: 5px 0; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th { background: #4472C4; color: white; padding: 10px; text-align: left; font-size: 11px; font-weight: bold; }
            td { padding: 8px; border-bottom: 1px solid #ddd; font-size: 10px; }
            tr:nth-child(even) { background: #f9f9f9; }
            .footer { text-align: center; font-size: 10px; color: #999; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; }
            .success { color: #28a745; }
            .warning { color: #ffc107; }
            .info { color: #17a2b8; }
            .error { color: #dc3545; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>SecureVision CCTV Monitoring System</h1>
                <p>Activity Log Report</p>
            </div>
            
            <div class="info-box">
                <p><strong>Report Generated:</strong> <?php echo date('Y-m-d H:i:s'); ?></p>
                <p><strong>Period:</strong> <?php echo $dateFrom; ?> to <?php echo $dateTo; ?></p>
                <p><strong>Generated By:</strong> <?php echo isset($_SESSION['user_name']) ? htmlspecialchars($_SESSION['user_name']) : 'System'; ?></p>
                <p><strong>Total Records:</strong> <?php echo count($data); ?></p>
            </div>
            
            <table>
                <thead>
                    <tr>
                        <th>Time</th>
                        <th>User</th>
                        <th>Role</th>
                        <th>Action</th>
                        <th>Details</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data as $row): ?>
                    <tr>
                        <td><?php echo htmlspecialchars($row['time']); ?></td>
                        <td><?php echo htmlspecialchars($row['user']); ?></td>
                        <td><?php echo htmlspecialchars($row['role']); ?></td>
                        <td><?php echo htmlspecialchars($row['action']); ?></td>
                        <td><?php echo htmlspecialchars($row['details']); ?></td>
                        <td class="<?php echo $row['status']; ?>"><?php echo ucfirst($row['status']); ?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            
            <div class="footer">
                <p>This is an automated report generated by SecureVision. For more information, visit: https://securevision.local</p>
                <p>© 2026 SecureVision. All rights reserved.</p>
            </div>
        </div>
    </body>
    </html>
    <?php
    
    $html = ob_get_clean();
    
    // For a full PDF implementation, use TCPDF or similar
    // For now, return HTML that can be printed to PDF
    header('Content-Type: text/html');
    header('Content-Disposition: attachment; filename="activity-report-' . date('Y-m-d-His') . '.html"');
    echo $html;
    exit;
}

function sanitize($input) {
    return htmlspecialchars(trim($input), ENT_QUOTES, 'UTF-8');
}
?>


